// <auto-generated />
using InsightDDD.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InsightDDD.Migrations
{
    [DbContext(typeof(InsightDbContext))]
    [Migration("20240523183418_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.5");

            modelBuilder.Entity("InsightDDD.Models.MediaDetail", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("TEXT");

                    b.Property<string>("caption")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("likeCount")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "like_count");

                    b.Property<string>("mediaUrl")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "media_url");

                    b.HasKey("id");

                    b.ToTable("MediaDetail");
                });
#pragma warning restore 612, 618
        }
    }
}
